/*
CREARE UNA CLASSE LOGGER CHE PERMETTE DI SCRIVERE MESSAGGI DI LOG
SU PIU' FILES. IN PARTICOLARE LA CLASSE AVRA' 4 LIVELLI DI LOG:
- WARNING
- INFO
- ERROR
- DEBUG

E 4 METODI CHE PERMETTONO DI SCRIVERE UN MESSAGGIO SUL RECIPROCO FILE.
(NOTA CHE IL FILE PUO' ANCHE ESSERE LO STESO).

LE FUNZIONI DI LOG DEVONO PERMETTERE DI STAMPARE UN QUALUNQUE TIPO.

NON SOLO MA DEVE ESSERE POSSIBILE SCRIVERE SUL LIVELLO DI "DEFAULT" USANDO
L'OPERATORE <<. E QUINDI ANCHE BISOGNA POTER CAMBIARE IL LIVELLO DI DEFAULT.
*/
