/*

SCRIVERE UNA CLASSE ASTRATTA FORMA CHE DEFINISCE UN METODO PER OTTENERE IL PERIMETRO DELLA FORMA
ED UNO PER OTTENERE L'AREA.

POI DEFINIRE LE CLASSI:
- CERCHIO
- RETTANGOLO
- PARALLELOGRAMMA
- QUADRATO
- TRIANGOLO

IN MODO TALE CHE QUESTE IMPLEMENTINO I METODI DELL'INTERFACCIA.

NEL MAIN CHIEDERE ALL'UTENTE DI CREARE LA FORMA CHE DESIDERA.
CONSERVARE QUESTA FORMA IN UNA COLLEZIONE.
E PERMETTERE ALL'UTENTE DI POTER VISUALIZZARE IL PERIMETRO E L'AREA DI QUALUNQUA FORMA PRECEDENTEMENTE INSERITA.

*/